# Generated by Django 5.2.6 on 2025-09-12 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="Task title")),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="Task description"),
                ),
                ("is_done", models.BooleanField(default=False, verbose_name="Is done")),
                ("dead_line", models.DateTimeField(verbose_name="Task dead line time")),
                ("is_active", models.BooleanField(verbose_name="Is valid task")),
            ],
        ),
    ]
