# Generated by Django 5.2.6 on 2025-09-12 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="task",
            name="is_active",
            field=models.BooleanField(verbose_name="Is valid"),
        ),
    ]
